/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package qx.leizige.gradle.example.app;

class MessageUtils {
    public static String getMessage() {
        return "Hello      World!";
    }
}
